### ISSUE TITLE
How to do real-time video upscaling

### ISSUE THREAD

**Issue by nitinjs** [HelpSeeker/FSRCNN-TensorFlow#3]
How to do real-time video upscaling using FSRCNN?

**Comment by HelpSeeker** [comment]
For mpv:

1. Download the shader file (.glsl) from the release page
2. Move it to a convenient location on your PC (usually somewhere in your mpv config directory)
3. Open your [mpv configuration file](https://mpv.io/manual/master/#configuration-files)
4. Add `glsl-shader="<path to shader file>"` (e.g. `glsl-shader="~~/FSRCNNX_x2_16-0-4-1_enhance.glsl"`; see also [special path options](https://mpv.io/manual/master/#paths))

This will automatically load the shader the next time your start mpv. It will only get applied under certain conditions though. Most notably the scaling factor has to be 1.4 or higher. It also doesn't work for RGB content (e.g. if you view PNGs).

You can also set up mpv to toggle the shader whenever you want it, but that takes more setup. If you want a short tutorial on that as well, just let me know.
